apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-7pnz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-7pnz
    app.kubernetes.io/part-of: ci10t-777-0093-app
  name: devfile-sample-7pnz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-7pnz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-7pnz
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0093-tenant/ci10t-777-0093-app/devfile-sample-7pnz@sha256:2bc19c41f5134680f8c855aaf5ac292977f705c7919c97d75d846b36c4d5ad61
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
