apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7pnz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0093-tenant/ci10t-777-0093-app/devfile-sample-7pnz@sha256:2bc19c41f5134680f8c855aaf5ac292977f705c7919c97d75d846b36c4d5ad61
        name: my-nodejs
        resources: {}
status: {}
